import { Track } from '../store/slices/playerSlice';
import { Playlist } from '../store/slices/playlistSlice';

// Mock tracks data
const tracks: Track[] = [
  {
    id: 'track-1',
    title: 'Blinding Lights',
    artist: 'The Weeknd',
    album: 'After Hours',
    duration: 203,
    coverArt: 'https://images.pexels.com/photos/1763075/pexels-photo-1763075.jpeg?auto=compress&cs=tinysrgb&w=300',
    serviceId: 'spotify-1',
    serviceName: 'spotify',
  },
  {
    id: 'track-2',
    title: 'Save Your Tears',
    artist: 'The Weeknd',
    album: 'After Hours',
    duration: 215,
    coverArt: 'https://images.pexels.com/photos/3756766/pexels-photo-3756766.jpeg?auto=compress&cs=tinysrgb&w=300',
    serviceId: 'spotify-2',
    serviceName: 'spotify',
  },
  {
    id: 'track-3',
    title: 'Levitating',
    artist: 'Dua Lipa',
    album: 'Future Nostalgia',
    duration: 203,
    coverArt: 'https://images.pexels.com/photos/3971985/pexels-photo-3971985.jpeg?auto=compress&cs=tinysrgb&w=300',
    serviceId: 'spotify-3',
    serviceName: 'spotify',
  },
  {
    id: 'track-4',
    title: 'Don\'t Start Now',
    artist: 'Dua Lipa',
    album: 'Future Nostalgia',
    duration: 183,
    coverArt: 'https://images.pexels.com/photos/1699161/pexels-photo-1699161.jpeg?auto=compress&cs=tinysrgb&w=300',
    serviceId: 'spotify-4',
    serviceName: 'spotify',
  },
  {
    id: 'track-5',
    title: 'Better Off Alone',
    artist: 'Alice Deejay',
    album: 'Who Needs Guitars Anyway?',
    duration: 177,
    coverArt: 'https://images.pexels.com/photos/1190298/pexels-photo-1190298.jpeg?auto=compress&cs=tinysrgb&w=300',
    serviceId: 'soundcloud-1',
    serviceName: 'soundcloud',
  },
  {
    id: 'track-6',
    title: 'When Love Takes Over',
    artist: 'David Guetta ft. Kelly Rowland',
    album: 'One Love',
    duration: 192,
    coverArt: 'https://images.pexels.com/photos/210922/pexels-photo-210922.jpeg?auto=compress&cs=tinysrgb&w=300',
    serviceId: 'deezer-1',
    serviceName: 'deezer',
  },
  {
    id: 'track-7',
    title: 'Summer of Love',
    artist: 'Calvin Harris',
    album: 'Motion',
    duration: 208,
    coverArt: 'https://images.pexels.com/photos/1701202/pexels-photo-1701202.jpeg?auto=compress&cs=tinysrgb&w=300',
    serviceId: 'deezer-2',
    serviceName: 'deezer',
  },
  {
    id: 'track-8',
    title: 'This Is What You Came For',
    artist: 'Calvin Harris ft. Rihanna',
    album: 'This Is What You Came For',
    duration: 222,
    coverArt: 'https://images.pexels.com/photos/167092/pexels-photo-167092.jpeg?auto=compress&cs=tinysrgb&w=300',
    serviceId: 'spotify-5',
    serviceName: 'spotify',
  },
  {
    id: 'track-9',
    title: 'Lean On',
    artist: 'Major Lazer & DJ Snake ft. MØ',
    album: 'Peace Is the Mission',
    duration: 176,
    coverArt: 'https://images.pexels.com/photos/1694900/pexels-photo-1694900.jpeg?auto=compress&cs=tinysrgb&w=300',
    serviceId: 'soundcloud-2',
    serviceName: 'soundcloud',
  },
  {
    id: 'track-10',
    title: 'Don\'t You Worry Child',
    artist: 'Swedish House Mafia ft. John Martin',
    album: 'Until Now',
    duration: 212,
    coverArt: 'https://images.pexels.com/photos/164693/pexels-photo-164693.jpeg?auto=compress&cs=tinysrgb&w=300',
    serviceId: 'deezer-3',
    serviceName: 'deezer',
  },
  {
    id: 'track-11',
    title: 'Titanium',
    artist: 'David Guetta ft. Sia',
    album: 'Nothing but the Beat',
    duration: 245,
    coverArt: 'https://images.pexels.com/photos/3255761/pexels-photo-3255761.jpeg?auto=compress&cs=tinysrgb&w=300',
    serviceId: 'spotify-6',
    serviceName: 'spotify',
  },
  {
    id: 'track-12',
    title: 'Levels',
    artist: 'Avicii',
    album: 'Levels',
    duration: 210,
    coverArt: 'https://images.pexels.com/photos/1699161/pexels-photo-1699161.jpeg?auto=compress&cs=tinysrgb&w=300',
    serviceId: 'soundcloud-3',
    serviceName: 'soundcloud',
  },
];

// Mock playlists data
const playlists: Playlist[] = [
  {
    id: 'playlist-1',
    name: 'EDM Hits',
    description: 'Best electronic dance music hits of all time',
    coverArt: 'https://images.pexels.com/photos/1540406/pexels-photo-1540406.jpeg?auto=compress&cs=tinysrgb&w=300',
    owner: 'Demo User',
    tracks: [tracks[4], tracks[5], tracks[6], tracks[7], tracks[8], tracks[9], tracks[10], tracks[11]],
    serviceName: 'harmonized',
    isPublic: true,
    isCollaborative: false,
    createdAt: '2025-01-15T10:00:00.000Z',
    updatedAt: '2025-03-20T14:30:00.000Z',
  },
  {
    id: 'playlist-2',
    name: 'Workout Mix',
    description: 'High energy tracks to fuel your workout',
    coverArt: 'https://images.pexels.com/photos/2261/food-man-person-face.jpg?auto=compress&cs=tinysrgb&w=300',
    owner: 'Demo User',
    tracks: [tracks[0], tracks[2], tracks[5], tracks[7], tracks[9]],
    serviceName: 'spotify',
    isPublic: true,
    isCollaborative: false,
    createdAt: '2025-02-10T08:45:00.000Z',
    updatedAt: '2025-03-15T11:20:00.000Z',
  },
  {
    id: 'playlist-3',
    name: 'Chill Vibes',
    description: 'Relaxing tunes for your downtime',
    coverArt: 'https://images.pexels.com/photos/3961942/pexels-photo-3961942.jpeg?auto=compress&cs=tinysrgb&w=300',
    owner: 'Demo User',
    tracks: [tracks[1], tracks[3], tracks[8]],
    serviceName: 'soundcloud',
    isPublic: false,
    isCollaborative: false,
    createdAt: '2025-01-05T15:30:00.000Z',
    updatedAt: '2025-03-18T09:15:00.000Z',
  },
  {
    id: 'playlist-4',
    name: 'Weekend Party',
    description: 'Ultimate party playlist for the weekend',
    coverArt: 'https://images.pexels.com/photos/1190298/pexels-photo-1190298.jpeg?auto=compress&cs=tinysrgb&w=300',
    owner: 'Demo User',
    tracks: [tracks[0], tracks[2], tracks[4], tracks[6], tracks[8], tracks[10]],
    serviceName: 'deezer',
    isPublic: true,
    isCollaborative: true,
    createdAt: '2025-03-01T20:00:00.000Z',
    updatedAt: '2025-03-22T12:45:00.000Z',
  },
  {
    id: 'playlist-5',
    name: 'Throwback Classics',
    description: 'Classic hits from the past decades',
    coverArt: 'https://images.pexels.com/photos/167092/pexels-photo-167092.jpeg?auto=compress&cs=tinysrgb&w=300',
    owner: 'Demo User',
    tracks: [tracks[4], tracks[9], tracks[11]],
    serviceName: 'harmonized',
    isPublic: true,
    isCollaborative: false,
    createdAt: '2024-12-20T14:15:00.000Z',
    updatedAt: '2025-03-10T08:30:00.000Z',
  },
];

export default {
  tracks,
  playlists,
};